distributable:
  url: https://github.com/yarnpkg/berry/archive/refs/tags/@yarnpkg/cli/{{version}}.tar.gz
  strip-components: 1

versions:
  github: yarnpkg/berry

provides:
  - bin/yarn
  # no idea why yarn provides a shortcut of yarnpkg but it errors in mac
  # - scripts/bin/yarnpkg
  - bin/yarnpkg

dependencies:
  nodejs.org: '>=18.3'

build:
  script: |
    rm scripts/bin/yarnpkg || true
    cp -r . {{prefix}}
    mkdir -p {{prefix}}/bin

    yarnScript=$(cat scripts/bin/yarn)
    replace="../.."
    next=".."
    echo "${yarnScript/$replace/"$next"}" >> {{prefix}}/bin/yarn
    chmod +x {{prefix}}/bin/yarn

    cp {{prefix}}/bin/yarn {{prefix}}/bin/yarnpkg

    if test "{{hw.platform}}" = "linux"; then
      $SUDO apt-get --yes install libatomic1
    fi

test:
  script: |
    yarn --version
    yarnpkg --version
    yarn add jquery