distributable:
  url: https://github.com/yarnpkg/berry/archive/refs/tags/@yarnpkg/cli/{{version}}.tar.gz
  strip-components: 1

versions:
  - yarnpkg/berry

provides:
  - scripts/bin/yarn
  - scripts/bin/yarnpkg

dependencies:
  nodejs.org: '>=16'

build:
  script: |
    cp -r . {{prefix}}

test:
  script: |
    yarn --version
