distributable:
  url: https://yarnpkg.com/downloads/1.22.19/yarn-v{{version}}.tar.gz
  strip-components: 1

versions:
  github: yarnpkg/berry

provides:
  - bin/yarn
  - bin/yarnpkg

dependencies:
  nodejs.org: '>=16'

build:
  script: |
    cp -r . {{prefix}}

test:
  script: |
    yarn --version
