distributable:
  url: https://registry.npmjs.org/pnpm/-/pnpm-{{version}}.tgz
  strip-components: 1

versions:
  github: pnpm/pnpm

provides:
  - bin/pnpm
  - bin/pnpx

dependencies:
  nodejs.org: '>=16'

build:
  script:
    node . install --global --prefix={{prefix}}

test:
  script: |
    pnpm doctor
    pnpx --version