distributable:
  url: https://registry.npmjs.org/pnpm/-/pnpm-{{version}}.tgz
  strip-components: 1

versions:
  github: pnpm/pnpm
  strip: /^pnpm /

provides:
  - bin/pnpm
  - bin/pnpx

dependencies:
  nodejs.org: '>=16'
  npmjs.com: '>=8'

build:
  script: |
    # npm install --prefix {{prefix}} . # this works for build
    cp bin/pnpm.cjs bin/pnpm
    cp bin/pnpx.cjs bin/pnpx
    cp -r . {{prefix}}

test:
  script: |
    pnpm doctor
    pnpx --version