distributable:
  url: https://registry.npmjs.org/pnpm/-/pnpm-{{version}}.tgz
  strip-components: 1

versions:
  github: pnpm/pnpm

provides:
  - bin/pnpm.cjs
  - bin/pnpx.cjs

dependencies:
  nodejs.org: '>=16'
  npmjs.com: '>=8'

build:
  script: |
    npm install --prefix {{prefix}} .
    # export PNPM_HOME=root/Library/pnpm
    # export PATH="$PNPM_HOME:$PATH";
    # export PATH="$(pwd)/bin:$PATH";

test:
  script: |
    pnpm doctor
    pnpx --version