distributable:
  url: https://github.com/vim/vim/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: vim/vim/tags
  strip: /v/


provides:
  - bin/vim
  - bin/vi

dependencies:
  python.org: '>=3.11'
  lua.org: '>=5.4'
  invisible-island.net/ncurses: '>=6.3'
  perl.org: '>=5.36'
  ruby-lang.org: '>=3.2'
build:
  dependencies:
    gnu.org/make: ^4.3
  script: |
    ./configure \
      --prefix={{prefix}} \
      --enable-multibyte \
      --with-tlib=ncurses \
      --with-compiledby=tea.xyz \
      --enable-cscope \
      --enable-terminal \
      --enable-perlinterp \
      --enable-rubyinterp \
      --enable-python3interp \
      --disable-gui \
      --without-x \
      --enable-luainterp
    make
    make install prefix={{prefix}}
test:
  script: |
    vim --version
    vi --version
    echo "hello world" >> test.txt
    echo ":s/hello/test/" >> commands.vim
    echo ":wq" >> commands.vim
    vim -T dumb -S commands.vim test.txt
    test "$(cat test.txt)" = "test world"