distributable:
  url: https://github.com/create-dmg/create-dmg/archive/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: create-dmg/create-dmg/tags
  strip: /^v/

provides:
  - bin/create-dmg

dependencies:
  tea.xyz/gx/cc: c99

build:
  script: |
    if test "{{hw.platform}}" != "darwin"; then
      mkdir -p {{prefix}}
      echo "create-dmg is only supported on mac" >> {{prefix}}/mac-only
      exit 0
    fi
    mkdir -p {{prefix}}/bin
    cp create-dmg {{prefix}}/bin
    mkdir -p {{prefix}}/share/create-dmg
    cp -r support {{prefix}}/share/create-dmg
    cp -r tests {{prefix}}/share/create-dmg
    cp -r examples {{prefix}}/share/create-dmg
test: |
  if test "{{hw.platform}}" = "darwin"; then
    create-dmg --version
    touch Brew-Eula.txt
    echo "Eula" >> Brew-Eula.txt
    mkdir -p Test-Source
    mkdir -p Test-Source/Brew.app
    create-dmg --sandbox-safe --eula Brew-Eula.txt Brew-Test.dmg Test-Source
  fi